version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/client.ccd.dev.scale360.solutions:/etc/nginx/certs

  web:
    build: .
    image: react-webrtc
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=client.ccd.dev.scale360.solutions
      - VIRTUAL_PROTO=https